# Generated by Django 4.2.7 on 2023-12-18 11:16

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='listJson',
            field=models.JSONField(default=builtins.id),
            preserve_default=False,
        ),
    ]
