# Generated by Django 4.2.7 on 2023-12-19 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0002_user_package_listjson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='listJson',
        ),
        migrations.AlterField(
            model_name='package',
            name='quantity',
            field=models.JSONField(),
        ),
    ]
