# Generated by Django 4.2.7 on 2023-12-19 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0003_remove_package_listjson_alter_package_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
